version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/New_York"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/New_York"
